name: image_build_all
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        DEVICE: [rock3a]
        EDITION: [gnome,kde-plasma,mate,minimal,sway,xfce]
        BRANCH: [stable]
    steps:
      -
        id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: '25.MM'
      -
        id: image-build
        uses: supdrewin/manjaro-arm-rootfs@master
        with:
          device: ${{ matrix.device }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          version: ${{ steps.time.outputs.time }}
      -
        name: Release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ${{ env.FILE_PATH }}
            ${{ env.FILE_SHA256 }}
